__include__: [
  'coco_detection.yml',
  'runtime.yml',
  'dataloader.yml',
  'optimizer.yml',
  'race6d_r50vd_best.yml',
]

output_dir: ./output/race6d_r50vd_pose_rgbd
coco_path: ./
category_file: ./pose_dataset2coco_category.yml
num_classes: 4
eval_spatial_size:
- 480
- 640
RACE6D:
  backbone: PResNet_depth
PResNet_depth:
  depth: 50
  variant: d
  freeze_at: -1
  return_idx:
  - 1
  - 2
  - 3
  num_stages: 4
  freeze_norm: false
  pretrained: true
  in_chans: 4
HybridEncoder:
  in_channels:
  - 512
  - 1024
  - 2048
  feat_strides:
  - 8
  - 16
  - 32
  use_encoder_idx:
  - 2
  num_encoder_layers: 1
  nhead: 8
  hidden_dim: 256
  depth_mult: 0.67
  enc_act: quick_gelu
RACE6DTransformer_DQE:
  feat_channels:
  - 256
  - 256
  - 256
  feat_strides:
  - 8
  - 16
  - 32
  hidden_dim: 256
  num_levels: 3
  num_points:
  - 3
  - 6
  - 3
  num_layers: 3
  vis_enc: true
  num_queries: 20
  eval_idx: -1
  activation: quick_gelu
  mlp_act: quick_gelu
  r_min: 0.5
  r_max: 2.0
RACE6DPostProcessor:
  num_top_queries: 20
  vis_enc: true
  remap_mscoco_category: false
RACE6DCriterion_addr:
  weight_dict:
    loss_vfl: 1
    loss_bbox: 5
    loss_giou: 2
    loss_keypoints: 1
    loss_oks: 1
    loss_cr: 0.1
    loss_pose: 5
  losses:
  - vfl
  - boxes
  - pose
  - keypoint
  alpha: 0.75
  gamma_pos: 1.0
  gamma_neg: 2.0
  matcher:
    type: HungarianMatcher
    weight_dict:
      cost_class: 2
      cost_bbox: 5
      cost_giou: 2
    alpha: 0.25
    gamma: 2.0
epoches: 100
checkpoint_freq: 5
print_freq: 20
progress_bar: true
lr_scheduler:
  type: FlatCosineAnnealingLR
  T_max: 50
  lr_gamma: 0.5
  warmup_iter: 1000
  flat_epochs: 5
  no_aug_epochs: 10
train_dataloader:
  dataset:
    img_folder: ./my_data/pose_rgbd_race6d/rgb
    ann_file: ./my_data/pose_rgbd_race6d/annotations/instances_train.json
    transforms:
      ops:
      - type: FilterSmallBoxLowVis
        min_size: 5
        min_visib: 0.1
      - type: RandomCoarseDropout
      - type: ColorJitter
      - type: RandomHSVAdjust
      - type: RandomSharpen
      - type: RandomMotionBlur
      - type: RandomGaussianBlur
      - type: RandomGaussianNoise
      - type: RandomAdditionalNoise
      - type: ConvertPILImage
        dtype: float32
        scale: true
      - type: ConvertBoxes
        fmt: cxcywh
        normalize: true
      policy:
        name: stop_epoch
        epoch: 40
        ops:
        - RandomCoarseDropout
        - ColorJitter
        - RandomHSVAdjust
        - RandomSharpen
        - RandomMotionBlur
        - RandomGaussianBlur
        - RandomGaussianNoise
        - RandomAdditionalNoise
    return_masks: true
    return_full_masks: false
    remap_mscoco_category: true
    return_depth: true
    depth_z_max_mm: 2000.0
    category_file: ./configs/race6d/include/pose_dataset2coco_category.yml
    coco_path: ./my_data/pose_rgbd_race6d
    need_aligned: false
  collate_fn:
    scales: null
  total_batch_size: 8
  num_workers: 0
val_dataloader:
  dataset:
    img_folder: ./my_data/pose_rgbd_race6d/rgb
    ann_file: ./my_data/pose_rgbd_race6d/annotations/instances_val.json
    transforms:
      ops:
      - type: FilterSmallBoxLowVis
        min_size: 5
        min_visib: 0.1
      - type: ConvertPILImage
        dtype: float32
        scale: true
      - type: ConvertBoxes
        fmt: cxcywh
        normalize: true
    return_masks: true
    return_full_masks: false
    remap_mscoco_category: true
    return_depth: true
    depth_z_max_mm: 2000.0
    category_file: ./configs/race6d/include/pose_dataset2coco_category.yml
    coco_path: ./my_data/pose_rgbd_race6d
    need_aligned: false
  total_batch_size: 1
  num_workers: 0
